export const pageTitles = {
  // "/dashboard": "Dashboard",

  "/nominal-roll": "Nominal Roll",
  "/spares": "Spares",
  "/spares/critical": "Critical Spare",
  "/spares/routine": "Spares for Routines",
  "/tools/routine": "Tools for Routines",
  "/spares/low-stock": "Low Stock Spares",
  "/tools/low-stock": "Low Stock Tools",
  "/documents/low-stock": "Low Stock Documents",
  "/temporary-issue/overdue": "Overdue Temporary Issue",
  "/temp-loan/overdue": "Overdue TY Loan",
  "/documents/overdue": "Overdue Documents",
  "/permanent/nac": "Pending for NAC",
  "/special/pts": "PTS",
  "/special/stordem": "STOREDEM / OPDEM",

  "/tools": "Tools & Accessories",
  "/tools/critical": "Critical / Special Tools",
  "/documents": "Documents Master",
  "/documents/issue": "Documents for Issue",
  "/documents/completed": "Documents Logs",
  "/temporary/temporary-issue": "Temporary Issue - Pending",
  "/temporary/completed": "Temporary Issue Logs",
  "/search": "Search",
  "/handheld": "Handheld Details",
  "/d787/original": "D787 Original",
  "/d787/amendment": "D787 Amendment",

  "/logs/pending-survey": "Survey Logs",
  "/logs/pending-demand": "Demand Logs",
  "/logs/pending-issue": "MO Issue Logs",
  "/logs/nac": "NAC Logs",
  "/logs/procurement": "Procurement Logs",
  "/logs/stock-update": "Stock Update Logs",
  "/logs/special-demand": "Special Demand Logs",

  "/permanent/pending-survey": "Pending for Survey",
  "/permanent/pending-demand": "Pending for Demand",
  "/permanent/pending-issue": "Pending for MO Issue",
  "/permanent/stock-update": "Pending for Stock Update",
  "/permanent/procurement": "Pending for Procurement",
  "/special/special-demand": "D787 Amendment Demand",
  "/permanent/complete": "Completed Issues",

  "/temporary": "Temporary Issue",

  "/temp-loan/pending": "TY Loan - Pending",
  "/temp-loan/complete": "TY Loan Logs",

  "/departments": "Departments",
  "/users": "Users",
  "/approvals": "Approvals",
  "/history": "Worklist History",

  "/successor-board/officer-incharge": "Officer Incharge",
  "/successor-board/storekeeper-incharge": "Storekeeper Incharge",
};
